include = [ "antifeatures.toml", "apps.toml", "categories.toml", "graveyard.toml", "rejectedlist.toml", "taplo.toml" ]

[formatting]
align_comments = false
array_auto_expand = false
compact_arrays = false
indent_tables = true
inline_table_expand = false
reorder_arrays = true
reorder_keys = true
