name: Add Added dates to the catalog files

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.YUNOHOST_BOT_TOKEN }}

    - uses: actions/checkout@v4
      with:
        repository: YunoHost/apps-tools
        path: tools
        fetch-depth: 0

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Python dependencies
      run: |
        pip3 install -r tools/requirements.txt

    - name: Add added dates to catalog files
      run: |
        ./tools/save_added_date.py --apps-dir .

    - uses: uncenter/setup-taplo@v1
    - run: taplo fmt

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automatically add dates to the catalog files"
        file_pattern: 'apps.toml wishlist.toml graveyard.toml'
        commit_user_name: yunohost-bot
        commit_user_email: yunohost-bot@users.noreply.github.com
        commit_author: 'yunohost-bot <yunohost-bot@users.noreply.github.com>'
