name: Catalog consistency checks

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: YunoHost/apps-tools
        path: tools
        fetch-depth: 0

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install Python dependencies
      run: |
        pip3 install -r tools/requirements.txt

    - name: Check TOML validity for apps.toml
      run: |
        python3 -c "import toml; toml.load(open('apps.toml'))"

    - name: Check all working apps have consistent app id / app url and categories
      run: |
        ./tools/catalog_linter.py --apps-dir .

    - name: Check the generation of the app catalog
      run: |
        ./tools/list_builder.py --apps-dir .
