name: Catalog consistency checks

on:
  pull_request:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install toml python lib
      run: |
        pip3 install toml jsonschema gitpython tqdm
    - name: Check TOML validity for apps.toml
      run: |
        python3 -c "import toml; toml.load(open('apps.toml'))"
    - name: Check all working apps have consistent app id / app url and categories
      run: |
        ./tools/catalog_linter.py
    - name: Check the generation of the app catalog
      run: |
        ./tools/list_builder.py
