name: Check formatting

on:
  pull_request:
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: uncenter/setup-taplo@v1

      - run: taplo fmt
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ":art: Format TOML with Taplo"
          file_pattern: 'apps.toml wishlist.toml graveyard.toml'
          commit_user_name: yunohost-bot
          commit_user_email: yunohost-bot@users.noreply.github.com
          commit_author: 'yunohost-bot <yunohost-bot@users.noreply.github.com>'
