name: Check formatting

on:
  pull_request:
  push:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: uncenter/setup-taplo@v1

      - run: taplo fmt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Format TOML with Taplo"
          commit-message: ":art: Format TOML with Taplo"
          body: |
            This pull request uses the [Taplo](https://taplo.tamasfe.dev) formatter.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/toml
