name: Run tests for make_readme.py

on: [push]

jobs:
  test:
    name: Run tests for make_readme.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up Python 3.9'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/readme_generator/requirements.txt
          pip install pytest
      - name: launch pytest
        run: cd tools/readme_generator && pytest tests
